### ISSUE TITLE
KeyError: User when using AssumedRole credentials

### ISSUE THREAD

**Issue by jwarren116** [RhinoSecurityLabs/pacu#105]
**Describe the bug**
When using keys from an AssumedRole I am unable to run the `iam__enum_permissions` module. If I didn't read the directions, please school me. I suspect the root of the issue is that my user and username aren't being populated in the identity because the ARN attached to the credentials doesn't fit the same format as a standard IAM user.

**To Reproduce**
1. Run the command 'set_keys' and set with Access Key, Secret Key, and Token for an Assumed Role
2. Run the command 'run iam__enum_permissions'
3. See error

The output of `whoami` is:
```
{
  "UserName": null,
  "UserArn": null,
  "AccountId": null,
  "UserId": null,
  "Roles": null,
  "Groups": null,
  "Policies": null,
  "AccessKeyId": "*****************",
  "SecretAccessKey": "*****************",
  "SessionToken": "*****************",
  "KeyAlias": "foo",
  "PermissionsConfirmed": null,
  "Permissions": {
    "Allow": {},
    "Deny": {}
  }
}
```

**Expected behavior**
The `iam__enum_permissions` module should complete successfully.

**Operating System (please complete the following information):**
 - OS + Version: OSX 10.11
 - Python version: 3.6.6

**Error log**

```
Traceback (most recent call last):
  File "pacu.py", line 1634, in run
    self.idle()
  File "pacu.py", line 1567, in idle
    self.parse_command(command)
  File "pacu.py", line 514, in parse_command
    self.parse_exec_module_command(command)
  File "pacu.py", line 828, in parse_exec_module_command
    self.exec_module(command)
  File "pacu.py", line 1049, in exec_module
    summary_data = module.main(command[2:], self)
  File "/Users/jwarren6/Apps/pacu/modules/iam__enum_permissions/main.py", line 126, in main
    user_name=identity['User']['UserName'],
<class 'KeyError'>: 'User'
```

**Comment by SpenGietz** [comment]
Awesome thank you for the report.

Currently the module is only working for actual IAM users (not Roles), so I will add that to my TODOs as this is very much needed. I'll update this as it is in progress and close it when it makes it into master.

**Comment by SpenGietz** [comment]
Merged into the dev branch. Will make it into master with a big merge once I finished a module I am working on (next couple days most likely)

**Comment by SpenGietz** [comment]
Merged into master! Both `iam__enum_permissions` and `iam__privesc_scan` were updated with role support
