### ISSUE TITLE
Ability from Pacu Operator Workstation Run Inline Shell Command

### ISSUE THREAD

**Issue by xee5ch** [RhinoSecurityLabs/pacu#107]
**Is your feature request related to a problem? Please describe.**
I want to be able to have a subcommand like `msfconsole execute` so I can run local shell commands.

**Describe the solution you'd like**
I would like to be able to run `cat`, `ls`, `grep`, or `jq` especially considering the extensive returns of aws cli output in JSON format.

**Describe alternatives you've considered**
There are plenty but this would increase the ergonomics and flexibility of the tool.

**Additional context**

**Comment by SpenGietz** [comment]
Sorry about the late response here! This is planned to be added at some point in the future, though I'm not exactly sure when. It definitely is a well-needed feature, so hopefully soon 👍 

I'll keep this issue updated when things progress.

**Comment by xee5ch** [comment]
I can give it a shot if you'd like. I know this is not core functionality anyway but that means you can focus on the good stuff.

**Comment by SpenGietz** [comment]
That'd be great, we always love pull requests!

**Comment by SpenGietz** [comment]
Pacu can now be run from the CLI!

```
python3 pacu.py --help
```
