### ISSUE TITLE
project organization question

### ISSUE THREAD

**Issue by mayn** [RhinoSecurityLabs/pacu#119]
I'm looking into addressing #72

I have a few questions:
1. Is there a purpose of boto3  and botocore being included in the project?
    - i.e is it modified or the dependencies were just checked in?
    - is it still needed if it is installed via requirements.txt
2. most python projects that are installed via pip have a top level module i.e
```
pacu/
└── pacu
    ├── core
    ├── modules
    └── pp_modules
```

vs the current
```
pacu/
├── core
├── modules
├── pp_modules
``` 
and are you guys open to this type of change?
3. project versioning would need to be maintained, it doesn't look like you are currently versioning / maintaining changelog updates upon merging to master. Is this something you would be willing to start doing?

**Comment by SpenGietz** [comment]
1. Currently PacuProxy requires a modified version of botocore to use SOCKS proxying for the boto3 client. There was recently a PR made into botocore that possibly could have fixed this so we wouldn't need an edited version, but I haven't had time to test that yet.

2. Wouldn't be opposed to this if it would help it become pip installable

3. This is something we have discussed and are definitely open to. We haven't come up with a good solution to implement yet, so a standard way of doing so would be great

**Comment by SpenGietz** [comment]
Also, if I am available in the Pacu slack team (https://join.slack.com/t/pacu-cloudgoat/shared_invite/enQtNDE3OTk0MjA3NTA2LTUyNDBiNWI4ZDhkMzRjZTQwODY5YjM0NjU4ODE5ZTk3ODc3MmM5YTMyNWU5NWQ4ODdiMWNhMzRjNWMwYWI4NzU) if you have any questions that come up during the process

**Comment by snixon** [comment]
I'm interested in this too, lets see if we can put a couple of ideas together.  Maybe the local shadowed botocore and boto3 could be renamed in the interim and moved to separate repos...

**Comment by SpenGietz** [comment]
I think it's about time to kill of PacuProxy and just remove the outdated libraries
