### ISSUE TITLE
Pacu cannot find AWS CLI

### ISSUE THREAD

**Issue by alexanderinsa** [RhinoSecurityLabs/pacu#120]
"I'm getting a aws: not found error."
Pacu is unable to find the AWS CLI binary if it is not in bourne shell profile path.

**To Reproduce**
1. Run any aws command within Pacu

**Expected behavior**
AWS commands should be ran against the installed AWS CLI.

**Operating System (please complete the following information):**
 - OS + Version: Kali
 - Python version: .2.7, 3.6

**Comment by SpenGietz** [comment]
@alexanderinsa was this ever resolved?
