### ISSUE TITLE
Download Public IP for All Ec2

### ISSUE THREAD

**Issue by random-robbie** [RhinoSecurityLabs/pacu#123]
**Describe the solution you'd like**
To be able to grab all EC2 public ip's and save them to a file.

**Describe alternatives you've considered**
```
aws ec2 describe-instances --filter "Name=instance-state-name,Values=running" --query "Reservations[].Instances[].[PublicIpAddress, Tags[?Key=='Name'].Value|[0]]" --output text
```

**Additional context**
this would allow to scan all other ip's and see if any other systems are vun.

**Comment by SpenGietz** [comment]
Great idea, I'll look into implementing this.

It'd be nice if it would also check other common services for other public IPs, like RDS as an example.

**Comment by DaveYesland** [comment]
This is currently possible with the following:
```
run ec2__enum --public-ips
data ec2 PublicIPs
```
