### ISSUE TITLE
s3__bucket_finder fails when calling aws cli

### ISSUE THREAD

**Issue by BBerastegui** [RhinoSecurityLabs/pacu#125]
**Describe the bug**
I tried to run the s3__bucket_finder module, and I found out that it was silently failing when calling the check_output in this line: https://github.com/RhinoSecurityLabs/pacu/blob/ac214d040aa706111c4c60d6dbf3d7ef398a3cb3/modules/s3__bucket_finder/main.py#L254

The only thing that I found out was that the command was exiting with an exit code of 1.

I called the same command via Python3 cli with no problem so I can't really find out what's happening here.

 - macOS High Sierra, Python 3.7.0

I was trying Pacu on a public "bounty": www.lambdashell.com

So my exact command and output can be shared here:

```
Pacu (LambdaShellSession:LambdaShellKeys) > run s3__bucket_finder -d lambdashell.com
  Running module s3__bucket_finder...
[s3__bucket_finder] This module requires external dependencies: ['https://github.com/aboul3la/Sublist3r.git', 'https://raw.githubusercontent.com/RhinoSecurityLabs/Security-Research/master/tools/aws-pentest-tools/s3/Buckets.txt']

Install them now? (y/n)

[s3__bucket_finder] Installing 2 total dependencies...
[s3__bucket_finder]   Dependency aboul3la/Sublist3r already installed.
[s3__bucket_finder]   Dependency Buckets.txt already installed.
[s3__bucket_finder] Dependencies finished installing.
[s3__bucket_finder] Generating bucket permutations list...
[s3__bucket_finder] Generated 2 bucket permutations. Beginning search across 16 regions.
Buckets searched: 100.0% (32/32)
[s3__bucket_finder] [+] Results:
[s3__bucket_finder]     Number of Buckets that Exist: 0
[s3__bucket_finder]     Number of Buckets that are Listable: 0
[s3__bucket_finder] s3__bucket_finder completed.

[s3__bucket_finder] MODULE SUMMARY:

  0 total buckets were found.
  0 buckets were found with viewable contents.
```

It was supposed to find one listable bucket called `www.lambdashell.com` on `us-west-1`.

**Comment by SpenGietz** [comment]
This module has so many problems that I decided to archive it for the time being
