### ISSUE TITLE
ec2__download_userdata: add filter for tags

### ISSUE THREAD

**Issue by rhodejo** [RhinoSecurityLabs/pacu#136]
**Is your feature request related to a problem? Please describe.**
Not related to a problem as the data (filtered EC2 instances) can be obtained by the aws cli and added to pacu (after some massaging). I have tested accounts with a very large number of instances (many being out of scope). A EC2 tag filter would help limit the scope of ec2__download_userdata pulls to specific (in scope) instances.

**Describe the solution you'd like**
Add an optional filter for tag names and their associated values to the ec2__download_userdata module. This would require the functionality of the following aws cli query: aws ec2 describe-instances --filters “Name=tag:NAME,Values=VALUE” --region SPECIFIED-REGION

This would allow for filtering on specific tags in large AWS accounts.

**Describe alternatives you've considered**
Use aws cli to get specific instances based on tags:

```
$ aws ec2 describe-instances --filters "Name=tag:TAG-NAME,Values=TAG-VALUE" --query "Reservations[*].Instances[*].InstanceId[]" --region SPECIFIED-REGION --output text > tagged.txt
$ sed -i $'s/\t/@SPECIFIED-REGION,/g' tagged.txt
```

This will output all tagged instances in comma-separated format with region-name for pacu consumption

**Comment by SpenGietz** [comment]
Great idea, I'll add it to our to-do list 👍
