### ISSUE TITLE
Add "data" command output to the cmd logs

### ISSUE THREAD

**Issue by nachobonilla** [RhinoSecurityLabs/pacu#140]
**Is your feature request related to a problem? Please describe.**

I couldn't found a way to export the information gathered through pacu.

**Describe the solution you'd like**

add the "data" command output to the "cmd_log.txt" so it is easier to export the results out of pacu.

**Describe alternatives you've considered**

Implement a "reporting" module which lets you save a file on the filesystem with the information of certain pairs of keys or session.

**Additional context**

**Comment by SpenGietz** [comment]
This has been solved somewhat in an unrelated update. Pacu can now be run from the command line, so you can redirect the output to a file. Here's an example of outputting the whole database:

```
python3 pacu.py --session Test --data all > all-pacu-data-for-Test-session.json
```

Closing this issue, but feel free to reopen if you don't think this solves your problem.
