### ISSUE TITLE
Using AWS AssumeRole functionality with Modules - How?

### ISSUE THREAD

**Issue by br0kej** [RhinoSecurityLabs/pacu#143]
Currently trying to get the `iam__privesc_scan` module working and running into some assume role problems. Within our accounts, we have a centralised IAM account that contains user's and then roles which enable access to the other accounts.

I have configured my /.aws/credentials file with the required access keys etc and it works with other tooling that uses the sts service but everytime I run the `iam__privesc_scan` it keeps returning permission related problems for the central IAM account and not the intended AssumeRole account.

Is there a flag I am missing to direct pacu to execute the module as a specific role?

**Comment by SpenGietz** [comment]
I'm assuming that you have imported the keys that you use to assume a role and not the actual role credentials, is that right?

Pacu doesn't have a feature to auto-assume a role, so you would need to manually assume the role and add the access key ID, secret access key, and session token into Pacu.

That would be a great feature though to auto-assume a certain role when using certain keys, so I'll add it to our list for potential future updates!
