### ISSUE TITLE
Remove old sessions

### ISSUE THREAD

**Issue by Maleus** [RhinoSecurityLabs/pacu#144]
This tool is awesome, truly learning a lot with it.

I would like the ability to remove old sessions, especially when dealing with clients, I would prefer that old keys and information could be purged completely.

Thanks!

**Comment by SpenGietz** [comment]
Right now you can remove the session files, but you're right that they stay in the database. I'll look into this 👍

**Comment by SpenGietz** [comment]
This has been added! Thanks for the suggestion. Use "delete_session" to do it.
