### ISSUE TITLE
Can't run module and can't understand the issue

### ISSUE THREAD

**Issue by omershliva** [RhinoSecurityLabs/pacu#152]
After setting up cloudgoat, trying to run iam__enum_permissions and getting the following errors:

Pacu (yes:bob) > run iam__enum_permissions 
  Running module iam__enum_permissions...
[iam__enum_permissions] Failed to discover the current users username, enter it now or Ctrl+C to exit the module: bob
[iam__enum_permissions] Confirming permissions for users:
[iam__enum_permissions]   bob...
[iam__enum_permissions]     List groups for user failed
[iam__enum_permissions]       FAILURE: MISSING REQUIRED AWS PERMISSIONS
[iam__enum_permissions]     List user policies failed
[iam__enum_permissions]       FAILURE: MISSING REQUIRED AWS PERMISSIONS
[iam__enum_permissions]     List attached user policies failed
[iam__enum_permissions]       FAILURE: MISSING REQUIRED AWS PERMISSIONS
[iam__enum_permissions]     Confirmed Permissions for bob
[iam__enum_permissions] iam__enum_permissions completed.

[iam__enum_permissions] MODULE SUMMARY:

  Confirmed permissions for 0 user(s).
  Confirmed permissions for 0 role(s).

**Comment by SpenGietz** [comment]
This means your user does not have permissions to make the API calls that iam__enum_permissions is trying to make. Double check the permissions of the user to make sure it has IAM read/list permissions.
