### ISSUE TITLE
Upgrade the SQLAlchemy to 1.3.6 in requirement.txt for Python3.8 Windows 

### ISSUE THREAD

**Issue by aspir** [RhinoSecurityLabs/pacu#153]
Trying to install the package using the requirements.txt and running it on Python3.8 windows fails.
This is because the version of SQLAlchemy which doesn't officially supports Python3.8
https://github.com/python/pyperformance/pull/64

**Comment by SpenGietz** [comment]
Have you run into any issues with Python 3.8 and/or the upgraded SQLAlchemy version?

**Comment by SpenGietz** [comment]
Resolved in this PR: https://github.com/RhinoSecurityLabs/pacu/pull/164

Will close this issue once it's in master
