### ISSUE TITLE
 pacu/install.sh incorrectly catches python 3.7.7 as not meeting the minimum requirement

### ISSUE THREAD

**Issue by davidokeyode** [RhinoSecurityLabs/pacu#178]
pacu/install.sh incorrectly catches python 3.7.7 as not meeting the minimum python 3 requirement of 3.5

sh pacu/install.sh
[ + ] Checking Python version . . .
[ $ ] python3 --version
Python 3.7.7
pacu/install.sh: 16: [[: not found
[ - ] Pacu requires Python to be installed at version 3.5 or higher. Your version is: Python 3.7.7
Please install Python version 3.5 or higher. https://www.python.org/downloads/

**Comment by SpenGietz** [comment]
Try using `bash install.sh` instead, I think the problem is that it's not understanding `[[` and is outputting the wrong error message.

**Comment by seb1055** [comment]
Closing this as resolved.
