### ISSUE TITLE
lambda__enum doesn't paginate under certain conditions

### ISSUE THREAD

**Issue by SpenGietz** [RhinoSecurityLabs/pacu#184]
figure out why

**Comment by jdearmas** [comment]
This doesn't describe the issue well enough to reproduce/debug.

**Comment by RyanJarv** [comment]
@jdearmas 

I just happened to see this and remembered I had some notes laying around on various bugs in Pacu.

Will post this here in case it helps.

```
When key is used, the paginate function returns instead of paginating.

  * https://github.com/RhinoSecurityLabs/pacu/blob/master/pacu/modules/lambda__enum/main.py#L53

```
