### ISSUE TITLE
Feature request: Export keys to ~/.aws/credentials

### ISSUE THREAD

**Issue by SpenGietz** [RhinoSecurityLabs/pacu#185]
We can import keys from there but we can't export them

Also tie it directly into the `aws` command when run from within Pacu

**Comment by seb1055** [comment]
Code for exporting keys to ~/.aws/credentials was added in eecdbd4c41b4e47540ca876ddc91b2ff5df0a6ee. This commit does not provide integration with the aws command when run from pacu. Let's open another feature request that documents what integration would look like when running the aws command from within Pacu 😃.
