### ISSUE TITLE
Crash in enum__secerets when attempting to connect to us-east-1-fips

### ISSUE THREAD

**Issue by seb1055** [RhinoSecurityLabs/pacu#188]
When allowing enum__secerts to scan all regions it attempts to scan region us-east-1-fips which causes a crash. 
![image](https://user-images.githubusercontent.com/24581748/85437132-f4ed1780-b53e-11ea-8031-a23a56c1864a.png)

**Comment by manasmbellani** [comment]
Took a look at this - I think we need slightly better handling within the enum_secrets function - I will update code and do a pull request in a few hours.

**Comment by manasmbellani** [comment]
Issue starting @ line 145 of enum_secrets main.py module. Probably need to have better handling on the subsequent code as well.

```
Traceback (most recent call last):
  File "pacu.py", line 1561, in run_gui
    self.idle()
  File "pacu.py", line 1441, in idle
    self.idle()
  File "pacu.py", line 1441, in idle
    self.idle()
  File "pacu.py", line 1441, in idle
    self.idle()
  [Previous line repeated 19 more times]
  File "pacu.py", line 1439, in idle
    self.parse_command(command)
  File "pacu.py", line 464, in parse_command
    self.parse_exec_module_command(command)
  File "pacu.py", line 586, in parse_exec_module_command
    self.exec_module(command)
  File "pacu.py", line 859, in exec_module
    summary_data = module.main(command[2:], self)
  File "/opt/pacu_manasmbellani/modules/enum__secrets/main.py", line 145, 
in main
```

Generated with command:
```
 > run enum__secrets --region us-east-1-fips
```

**Comment by manasmbellani** [comment]
Hi @seb1055 I have added a fix in PR #194 for this issue. I have tested this on my side, and it appears to work fine. 
Please feel free to try it out by cloning pacu, and apply PR with command:
```
$ git fetch origin pull/194/head:fix_enum_secrets_crash
$ git checkout fix_enum_secrets_crash
```

**Comment by seb1055** [comment]
Thanks for the submission. I will check this out in a few hours and get back to you!

**Comment by malpais** [comment]
Also think can update boto3 via pip and should fix

**Comment by Leectan** [comment]
@manasmbellani @seb1055 this also occurs on other modules that loops through all the regions as well. Ran into a few myself, any suggestion on this? 

<img width="1020" alt="python3_8" src="https://user-images.githubusercontent.com/24819052/101658259-d4444b80-3a12-11eb-927f-65fadb6eebaf.png">
