### ISSUE TITLE
Feature Request - store ec2 userdata one instance per file

### ISSUE THREAD

**Issue by jchrisfarris** [RhinoSecurityLabs/pacu#19]
rather than putting all the enumerated userdata into one file with the instance_id@region on the line above, create one file per userdata, and then convert the \n and \t into newlines and tabs. This would make it much easier to read and determine what devs are doing with their user-data files...

**Comment by SpenGietz** [comment]
Very sorry about such a long turn around here. It finally has been merged to master!
