### ISSUE TITLE
sqlite3 no such table pacu session error

### ISSUE THREAD

**Issue by Leectan** [RhinoSecurityLabs/pacu#203]
sh-4.2$ python3 pacu.py --list-modules
/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/functions.py:67: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overriden.
  "is going to be overriden.".format(identifier)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: pacu_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pacu.py", line 1635, in <module>
    Main().run()
  File "pacu.py", line 1629, in run
    self.run_cli(args)
  File "pacu.py", line 1445, in run_cli
    sessions = self.database.query(PacuSession).all()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3174, in all
    return list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3330, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3355, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: pacu_session
[SQL: SELECT pacu_session.id AS pacu_session_id, pacu_session.created AS pacu_session_created, pacu_session.is_active AS pacu_session_is_active, pacu_session.name AS pacu_session_name, pacu_session.boto_user_agent AS pacu_session_boto_user_agent, pacu_session.key_alias AS pacu_session_key_alias, pacu_session.access_key_id AS pacu_session_access_key_id, pacu_session.secret_access_key AS pacu_session_secret_access_key, pacu_session.session_token AS pacu_session_session_token, pacu_session.session_regions AS pacu_session_session_regions, pacu_session."APIGateway" AS "pacu_session_APIGateway", pacu_session."CloudTrail" AS "pacu_session_CloudTrail", pacu_session."CloudWatch" AS "pacu_session_CloudWatch", pacu_session."CodeBuild" AS "pacu_session_CodeBuild", pacu_session."Config" AS "pacu_session_Config", pacu_session."DataPipeline" AS "pacu_session_DataPipeline", pacu_session."DynamoDB" AS "pacu_session_DynamoDB", pacu_session."EC2" AS "pacu_session_EC2", pacu_session."ECS" AS "pacu_session_ECS", pacu_session."Glue" AS "pacu_session_Glue", pacu_session."GuardDuty" AS "pacu_session_GuardDuty", pacu_session."IAM" AS "pacu_session_IAM", pacu_session."Inspector" AS "pacu_session_Inspector", pacu_session."Lambda" AS "pacu_session_Lambda", pacu_session."Lightsail" AS "pacu_session_Lightsail", pacu_session."S3" AS "pacu_session_S3", pacu_session."SecretsManager" AS "pacu_session_SecretsManager", pacu_session."SSM" AS "pacu_session_SSM", pacu_session."Shield" AS "pacu_session_Shield", pacu_session."VPC" AS "pacu_session_VPC", pacu_session."WAF" AS "pacu_session_WAF", pacu_session."WAFRegional" AS "pacu_session_WAFRegional", pacu_session."Account" AS "pacu_session_Account", pacu_session."AccountSpend" AS "pacu_session_AccountSpend"
FROM pacu_session]
(Background on this error at: http://sqlalche.me/e/e3q8)

sh-4.2$ python3 --version
Python 3.7.8

sh-4.2$ pip3 --version
pip 9.0.3 from /usr/lib/python3.7/site-packages (python 3.7)

sh-4.2$ aws --version
aws-cli/1.18.127 Python/3.7.8 Linux/4.14.186-146.268.amzn2.x86_64 botocore/1.17.50

**Comment by seb1055** [comment]
This was likely due to a recent update to Pacu's database structure. This update will break Pacu's database if you have used previous versions of Pacu. To fix this, rename/backup the old sqlite.db file and let a new one be generated on the next startup.

**Comment by Leectan** [comment]
@seb1055 tried above method, even rm the sqlite.db file and start fresh with cloning new repo local in different OS (mac and kali), still getting the same error. 

<img width="1007" alt="Cursor_and_bash" src="https://user-images.githubusercontent.com/24819052/101529221-4c9d0500-395e-11eb-8fd8-2a7fcdf9d264.png">


<img width="1020" alt="Cursor_and_bash" src="https://user-images.githubusercontent.com/24819052/101529296-62122f00-395e-11eb-8c01-24b6d2ea2791.png">

**Comment by Leectan** [comment]
remove all pip3 modules and reinstall with pip3 install -r requirement.txt doesn't help. Cloning new repo and make sure the sqlite.db is removed and let it generate a new one still getting same error. Running on different box (kali) still getting same error.

**Comment by Leectan** [comment]
Nvm, solved it. For those who might running into this. Clone pacu into new directory and create new virtenvironment for dependencies will solve this. Thanks

**Comment by ikspozd** [comment]
@Leectan can you provide additional details? I'm having same issue. Much appreciated!

**Comment by RyanJarv** [comment]
- @ikspozd This is likely from recent changes to the SQLite DB. We hope to get something in place to avoid this coming up in the future but for now, assuming you don't need the data in your current sessions it's easiest to move or delete the current DB and recreate it.

So something like:
> mv ~/.local/share/sqlite.db{,.bak}

And rerunning Pacu will resolve the issue. However the previous data will still only be in the moved sqlite db.

If you need to carry this data over let me know and I'll put together a better fix for you.

**Comment by ikspozd** [comment]
@RyanJarv - thanks for your prompt response. The pip install wasn't cutting it so I went the github route. The steps below resolved my issue.

#Create virtual environment
1) cd Environments (this is a just a folder to keep my virtual environments organized)
2) virtualenv PacuEnv (PacuEnv is the name I gave my virtual environment)
3) source PacuEnv/bin/activate (Connect to your virtual environment)

#Download and install Pacu dependencies in virtual environment

4) git clone https://github.com/RhinoSecurityLabs/pacu.git
5) cd pacu && pip install -r requirements.txt

#Start Pacu
6) ./cli.py
