### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by zhuxinkai** [RhinoSecurityLabs/pacu#211]
if urllib3 = 1.2.2 ,  File "/usr/local/lib/python3.6/site-packages/botocore/utils.py", line 30, in <module>
    from urllib3.util.url import IPV6_ADDRZ_RE
ImportError: cannot import name 'IPV6_ADDRZ_RE'

i faced this issue too
seemed like an issue with urllib3 version
using pip install urllib3==1.25.10 fixed my problem

**Comment by seb1055** [comment]
Thank you for the issue. #158 was merged updating urllib3 to 1.24.2
