### ISSUE TITLE
Gov US Regions Not Supported

### ISSUE THREAD

**Issue by ngkogkos** [RhinoSecurityLabs/pacu#215]
Hello,

Many thanks for this awesome tool. It appears that GovCloud specific regions are not supported by the tool:

```
Pacu (zzz:zzz) > set_regions us-gov-west-1
  us-gov-west-1 is not a valid region.
  Session regions not changed.
Pacu (zzz:zzz) > set_regions us-gov-east-1
  us-gov-east-1 is not a valid region.
  Session regions not changed.
```

I am uncertain if `update_regions` should work anyway in this case because those regions are part of AWS GovCloud https://aws.amazon.com/govcloud-us/ and not sure how update_regions works.

There's also a TODO comment in code for adding Gov regions as per below link, so I will leave this issue as a reminder perhaps, but please feel free to close it.

https://github.com/RhinoSecurityLabs/pacu/commit/bb16826f627dba03e0637756deb08ab3ae9222c9#diff-71dc51a9bdeb8f4ee57a94e2ad542f0ff2f74f2bfb23cd61eddf5b5e6652b84fR202

**Comment by ikspozd** [comment]
Would appreciate this feature enhancement :)

**Comment by ksummersill2** [comment]
Agree, would love the Gov Cloud region added.
