### ISSUE TITLE
pip3 install -r requirements.txt (or install.sh) installing ALL aws-cli versions

### ISSUE THREAD

**Issue by halfluke** [RhinoSecurityLabs/pacu#223]
I already have aws-cli version 2 installed.

Is the following normal?

Using cached awscli-1.18.134-py2.py3-none-any.whl (3.3 MB)
  Using cached awscli-1.18.133-py2.py3-none-any.whl (3.3 MB)
  Using cached awscli-1.18.132-py2.py3-none-any.whl (3.3 MB)
  Using cached awscli-1.18.131-py2.py3-none-any.whl (3.3 MB)
  Using cached awscli-1.18.130-py2.py3-none-any.whl (3.3 MB)
  Using cached awscli-1.18.129-py2.py3-none-any.whl (3.3 MB)
  Downloading awscli-1.18.128-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.1 MB/s 
  Downloading awscli-1.18.127-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.3 MB/s 
  Downloading awscli-1.18.126-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.3 MB/s 
  Downloading awscli-1.18.125-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 1.2 MB/s 
  Downloading awscli-1.18.124-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.3 MB/s 
  Downloading awscli-1.18.123-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.2 MB/s 
  Downloading awscli-1.18.122-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.0 MB/s 
  Downloading awscli-1.18.121-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.0 MB/s 
  Downloading awscli-1.18.120-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.4 MB/s 
  Downloading awscli-1.18.119-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 1.8 MB/s 
  Downloading awscli-1.18.118-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.0 MB/s 
  Downloading awscli-1.18.117-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.1 MB/s 
  Downloading awscli-1.18.116-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.1 MB/s 
  Downloading awscli-1.18.115-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.0 MB/s 
  Downloading awscli-1.18.114-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.2 MB/s 
  Downloading awscli-1.18.113-py2.py3-none-any.whl (3.3 
..................................

**Comment by RyanJarv** [comment]
I've noticed this happening well. I'm not entirely sure why it happens, or why it only sometimes happens.

Related to this I've been thinking we should remove the awscli dependency and using the one already installed on the system, if that doesn't exist then printing a message about how to install it I think makes sense.

**Comment by RyanJarv** [comment]
I believe this should be resolved now, do you mind letting us know if this is still happening?

**Comment by halfluke** [comment]
Brand new kali, I am trying to keep my python installation clean so I've created a virtualenv "Pacu".
┌──(Pacu)(root💀kali)-[~/Downloads/pacu]
└─# pip install -r requirements.txt
Collecting awscli==1.19.59
  Downloading awscli-1.19.59-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 2.5 MB/s 
Collecting boto3==1.17.59
  Downloading boto3-1.17.59-py2.py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 78.1 MB/s 
Collecting botocore==1.20.59
  Downloading botocore-1.20.59-py2.py3-none-any.whl (7.4 MB)
     |████████████████████████████████| 7.4 MB 23.3 MB/s 
Collecting certifi==2020.12.5
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 18.0 MB/s 
Collecting chardet==4.0.0
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 16.8 MB/s 
Collecting colorama==0.4.3
  Downloading colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting docutils==0.15.2
  Downloading docutils-0.15.2-py3-none-any.whl (547 kB)
     |████████████████████████████████| 547 kB 15.5 MB/s 
Collecting dsnap==1.0.0
  Downloading dsnap-1.0.0-py3-none-any.whl (15 kB)
Collecting idna==2.10
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 10.3 MB/s 
Collecting jmespath==0.10.0
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting pyasn1==0.4.8
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 13.6 MB/s 
Collecting python-dateutil==2.8.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 44.5 MB/s 
Collecting pyyaml==5.4.1
  Downloading PyYAML-5.4.1-cp39-cp39-manylinux1_x86_64.whl (630 kB)
     |████████████████████████████████| 630 kB 16.3 MB/s 
Collecting requests==2.25.1
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 4.6 MB/s 
Collecting rsa==4.7.2
  Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
Collecting s3transfer==0.4.2
  Downloading s3transfer-0.4.2-py2.py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 12.8 MB/s 
Collecting six==1.15.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting sqlalchemy-utils==0.36.8
  Downloading SQLAlchemy-Utils-0.36.8.tar.gz (138 kB)
     |████████████████████████████████| 138 kB 13.1 MB/s 
Collecting sqlalchemy==1.3.24
  Downloading SQLAlchemy-1.3.24-cp39-cp39-manylinux2010_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 47.6 MB/s 
Collecting typing-extensions==3.7.4.3
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting urllib3==1.26.5
  Downloading urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 19.9 MB/s 
Building wheels for collected packages: sqlalchemy-utils
  Building wheel for sqlalchemy-utils (setup.py) ... done
  Created wheel for sqlalchemy-utils: filename=SQLAlchemy_Utils-0.36.8-py2.py3-none-any.whl size=93237 sha256=b9498b7366d2269528dcb8159d29da1f4d254d19416fd2a0a6d51d0f17daf661
  Stored in directory: /root/.cache/pip/wheels/cc/a9/ec/d14efb7a25128ae89ce3fc5545dac6016306e75e60d6f0e499
Successfully built sqlalchemy-utils
Installing collected packages: six, urllib3, python-dateutil, jmespath, botocore, s3transfer, pyasn1, sqlalchemy, rsa, pyyaml, idna, docutils, colorama, chardet, certifi, boto3, typing-extensions, sqlalchemy-utils, requests, dsnap, awscli
Successfully installed awscli-1.19.59 boto3-1.17.59 botocore-1.20.59 certifi-2020.12.5 chardet-4.0.0 colorama-0.4.3 docutils-0.15.2 dsnap-1.0.0 idna-2.10 jmespath-0.10.0 pyasn1-0.4.8 python-dateutil-2.8.1 pyyaml-5.4.1 requests-2.25.1 rsa-4.7.2 s3transfer-0.4.2 six-1.15.0 sqlalchemy-1.3.24 sqlalchemy-utils-0.36.8 typing-extensions-3.7.4.3 urllib3-1.26.5

Looks good, just not using aws-cli 2... is that ok?

**Comment by RyanJarv** [comment]
Yeah, that should be fine, just will use V1 if you run the AWS command in Pacu, but you can always run the same thing in another shell with V2 installed if you want.

V2 isn't installed through pip so we'd need to figure out something else for that, although I'm personally thinking it makes more sense to remove that feature (although let us know if you find it useful for anything and think we should keep it).

**Comment by halfluke** [comment]
Thank you for your efforts!
