### ISSUE TITLE
Update wiki with new modules

### ISSUE THREAD

**Issue by RyanJarv** [RhinoSecurityLabs/pacu#243]
Several PR's where merged recently adding various modules, the page at https://github.com/RhinoSecurityLabs/pacu/wiki/Module-Details needs to be updated to reflect this.

**Comment by DaveYesland** [comment]
Adding this here to fix this: https://github.com/RhinoSecurityLabs/pacu/issues/300

**Comment by DaveYesland** [comment]
These have been updated
