### ISSUE TITLE
Initial installation error due to some missing requirements

### ISSUE THREAD

**Issue by MariaRusanova** [RhinoSecurityLabs/pacu#278]
Hello Team, 

Running the tool pacu on my environment (using Windows Terminal) gave me the following error: 

ERROR: Could not find a version that satisfies the requirement pacu (from versions: none)
ERROR: No matching distribution found for pacu

The full output is as follows below: 
C:\Users\rosenom\tools>pip3 install -U pacu
Defaulting to user installation because normal site-packages is not writeable
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /simple/pacu/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /simple/pacu/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /simple/pacu/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /simple/pacu/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /simple/pacu/
**ERROR: Could not find a version that satisfies the requirement pacu (from versions: none)
ERROR: No matching distribution found for pacu**

Without this command I can't proceed further. 
Could you please advise me what is missing on this step?

Thank you.
Regards,
Maria

**Comment by MariaRusanova** [comment]
After turn off my proxy and VPN the output is: 

C:\Users\rosenom\tools>pip3 install -U pacu
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pacu in c:\users\rosenom\appdata\roaming\python\python38\site-packages (1.0.3)
Requirement already satisfied: requests<3.0.0,>=2.25.1 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from pacu) (2.25.1)
Requirement already satisfied: botocore<2.0,>=1.16 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from pacu) (1.20.88)
Requirement already satisfied: typing-extensions<4.0.0.0,>=3.7.4.3 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from pacu) (3.10.0.0)
Requirement already satisfied: dsnap<2.0.0,>=1.0.0 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from pacu) (1.0.0)
Requirement already satisfied: urllib3<2.0.0,>=1.26.4 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from pacu) (1.26.5)
Requirement already satisfied: SQLAlchemy<1.4.0,>=1.3.0 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from pacu) (1.3.24)
Requirement already satisfied: boto3<2.0,>=1.16 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from pacu) (1.17.88)
Requirement already satisfied: awscli<2.0,>=1.18 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from pacu) (1.19.88)
Requirement already satisfied: SQLAlchemy-Utils<0.37.0,>=0.36.8 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from pacu) (0.36.8)
Requirement already satisfied: rsa<4.8,>=3.1.2 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from awscli<2.0,>=1.18->pacu) (4.7.2)
Requirement already satisfied: PyYAML<5.5,>=3.10 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from awscli<2.0,>=1.18->pacu) (5.4.1)
Requirement already satisfied: s3transfer<0.5.0,>=0.4.0 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from awscli<2.0,>=1.18->pacu) (0.4.2)
Requirement already satisfied: colorama<0.4.4,>=0.2.5 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from awscli<2.0,>=1.18->pacu) (0.4.3)
Requirement already satisfied: docutils<0.16,>=0.10 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from awscli<2.0,>=1.18->pacu) (0.15.2)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from botocore<2.0,>=1.16->pacu) (0.10.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from botocore<2.0,>=1.16->pacu) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0,>=1.16->pacu) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from requests<3.0.0,>=2.25.1->pacu) (2021.5.30)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from requests<3.0.0,>=2.25.1->pacu) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from requests<3.0.0,>=2.25.1->pacu) (2.10)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\rosenom\appdata\roaming\python\python38\site-packages (from rsa<4.8,>=3.1.2->awscli<2.0,>=1.18->pacu) (0.4.8)

**C:\Users\rosenom\tools>pacu
'pacu' is not recognized as an internal or external command,
operable program or batch file.**

There is still some issue that I don't understand fully.

**Comment by j0eblow** [comment]
Can you try:

`python3 -m pacu`

**Comment by MariaRusanova** [comment]
I run this command that way. 

C:\Users\rosenom>python3 -m pacu
**Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.**

The previous commands were executed successfuly. 

I tried also and withouth the parameter -m but still is not working. :(
If you can advise me further because I'm not sure how to pass this eeror.

**Comment by MariaRusanova** [comment]
with python -m pacu it is working in my case

**Comment by MariaRusanova** [comment]
I created a session but there is still an error with this tool. 

[2021-07-07 10:43:42] Pacu encountered an error while running the previous command. Check C:\Users\rosenom\.local\share\pacu\Maria/global_error_log.txt for technical details. [LOG LEVEL: MINIMAL]

    **<class 'requests.exceptions.ProxyError'>: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /RhinoSecurityLabs/pacu/master/pacu/last_update.txt (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))**

**Pacu is unable to start. Try backing up Pacu's sqlite.db file and deleting the old version. If the error persists, try reinstalling Pacu in a new directory.**

If you can try to help me how to figure out and resolve it. Thanks!

**Comment by MariaRusanova** [comment]
This is not relevant anymore as I found a way currently to work without my proxy and this issue was bypassed.
