### ISSUE TITLE
*Question* about function

### ISSUE THREAD

**Issue by gilstkos** [RhinoSecurityLabs/pacu#310]
In the pacu/pacu/modules/aws__enum_account/main.py and pacu/pacu/modules/aws__enum_spend/main.py 
There is a use of get_metric_statistics function but i couldn't find where it is defined and what does it do.
i would love some clarification about it

**Comment by RyanJarv** [comment]
Guessing you're referring to this line here?

https://github.com/RhinoSecurityLabs/pacu/blob/master/pacu/modules/aws__enum_account/main.py#L67

That would be from the boto3 library. Boto3 is a bit annoying in that it it's all dynamically defined, but the object being called is the cloudwatch client (defined here: https://github.com/RhinoSecurityLabs/pacu/blob/master/pacu/modules/aws__enum_account/main.py#L65). From there generally you want to reference the boto3 docs (and can find the reference for this function here: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudwatch.html#CloudWatch.Client.get_metric_statistics).
