### ISSUE TITLE
 In the iam__enum_permissions module, the value of summary_data ['users_confirmed'] cannot be incremented, so the stdout value is not appropriate.

### ISSUE THREAD

**Issue by r1ku-b** [RhinoSecurityLabs/pacu#321]
* When I run the iam__enum_permissions module for a user who has an inline policy attached but no managed policy attached, the correct value is not printed in the "MODULE SUMMARY" section.
* This is probably because the value of the `user ['PermissionsConfirmed']` flag in the source code has been overwritten in Flase.
* Even though I have found the user's permission, it is output as 0user (s) as shown below.
* ![image](https://user-images.githubusercontent.com/107228120/178452351-5c1c9fe4-4463-4fdf-aa2b-89cfdcab6185.png)
* I'm sorry if my assumption is wrong.

**Comment by DaveYesland** [comment]
Hey @r1ku-b,
I am having trouble reproducing this. Could you share the full Pacu command you are running? Are you running it from the user you are trying to enumerate or from a different user/role?

**Comment by DaveYesland** [comment]
Closing this for now. I am unable to reproduce, without more information I cannot fix it.
