### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by allymac121** [RhinoSecurityLabs/pacu#323]
pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Ignoring ansicon: markers 'platform_system == "Windows"' don't match your environment
Ignoring jinxed: markers 'platform_system == "Windows"' don't match your environment
Ignoring typing: markers 'python_version < "3.7"' don't match your environment
Collecting attrs==20.3.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting awscli==1.20.13
  Using cached awscli-1.20.13-py3-none-any.whl (3.7 MB)
Collecting blessed==1.17.6
  Using cached blessed-1.17.6-py2.py3-none-any.whl (76 kB)
Collecting boto3==1.18.13
  Using cached boto3-1.18.13-py3-none-any.whl (131 kB)
Collecting botocore==1.21.13
  Using cached botocore-1.21.13-py3-none-any.whl (7.8 MB)
Collecting certifi==2021.5.30
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting chalice==1.24.1
  Using cached chalice-1.24.1-py3-none-any.whl (388 kB)
Collecting charset-normalizer==2.0.4
  Using cached charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
Collecting click==7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting colorama==0.4.3
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting docutils==0.15.2
  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
Collecting dsnap==1.0.0
  Using cached dsnap-1.0.0-py3-none-any.whl (15 kB)
Collecting idna==3.2
  Using cached idna-3.2-py3-none-any.whl (59 kB)
Collecting inquirer==2.7.0
  Using cached inquirer-2.7.0-py2.py3-none-any.whl (31 kB)
Collecting jmespath==0.10.0
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting mypy-extensions==0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting pyasn1==0.4.8
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting python-dateutil==2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting python-editor==1.0.4
  Using cached python_editor-1.0.4-py3-none-any.whl (4.9 kB)
Requirement already satisfied: pyyaml==5.4.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 79)) (5.4.1)
Collecting readchar==2.0.1
  Using cached readchar-2.0.1-py3-none-any.whl (6.9 kB)
Collecting requests==2.26.0
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting rsa==4.7.2
  Using cached rsa-4.7.2-py3-none-any.whl (34 kB)
Collecting s3transfer==0.5.0
  Using cached s3transfer-0.5.0-py3-none-any.whl (79 kB)
Requirement already satisfied: six==1.16.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 121)) (1.16.0)
Collecting sqlalchemy-utils==0.36.8
  Using cached SQLAlchemy-Utils-0.36.8.tar.gz (138 kB)
  Preparing metadata (setup.py) ... done
Collecting sqlalchemy==1.3.24
  Using cached SQLAlchemy-1.3.24.tar.gz (6.4 MB)
  Preparing metadata (setup.py) ... done
Collecting typing-extensions==3.10.0.0
  Using cached typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Collecting urllib3==1.26.6
  Using cached urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting wcwidth==0.2.5
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (from chalice==1.24.1->-r requirements.txt (line 22)) (0.37.1)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from chalice==1.24.1->-r requirements.txt (line 22)) (59.6.0)
Collecting pip<21.3,>=9
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    pip<21.3,>=9 from https://files.pythonhosted.org/packages/ca/31/b88ef447d595963c01060998cb329251648acf4a067721b0452c45527eb8/pip-21.2.4-py3-none-any.whl#sha256=fa9ebb85d3fd607617c0c44aca302b1b45d87f9c2a1649b46c26167ca4296323 (from chalice==1.24.1->-r requirements.txt (line 22))

**Comment by DaveYesland** [comment]
This should be fixed with https://github.com/RhinoSecurityLabs/pacu/commit/e35a57eed82f9bf28dc8179668cab929eec0c815
