### ISSUE TITLE
generate console certificate error

### ISSUE THREAD

**Issue by cqrlhz** [RhinoSecurityLabs/pacu#349]
![捕获](https://github.com/RhinoSecurityLabs/pacu/assets/63200706/57b86bb3-3b6d-4934-bf8d-83506b3c8129)

**Comment by DaveYesland** [comment]
Hello,
Can you provide more information on what the issue with running Pacu is and at what step you encounter this error? 
The information provided is not enough to diagnose the problem.

Please include a description sufficient to reproduce the bug you found, including tracebacks and reproduction steps.

**Comment by DaveYesland** [comment]
Closing this for now, feel free to re-open with more information and we can try to look into it.
