### ISSUE TITLE
Update Regions

### ISSUE THREAD

**Issue by zeyad-sitech** [RhinoSecurityLabs/pacu#359]
Region list doesn't include `me-south-1`, `me-central-1`, although cannot update them using update_regions command

**Comment by DaveYesland** [comment]
Are you able to force these resion by just specifying them in the `--region` flag?

For example
`run ec2__enum --region me-south-1`

**Comment by zeyad-sitech** [comment]
i think i tried it but didn't work, i'll try again and let you know

**Comment by DaveYesland** [comment]
Yeah I think the region handling overall in Pacu need reworking also would include issues mentioned in #215. Hoping I can work on updates to region handling soon but not sure when that will be.
