### ISSUE TITLE
jq parser breaks pip installs on Windows

### ISSUE THREAD

**Issue by DaveYesland** [RhinoSecurityLabs/pacu#385]
I got this error when installing using `pip install -U pacu`
![image](https://github.com/RhinoSecurityLabs/pacu/assets/29385551/e7fc18c4-f82a-460b-9742-aa36519719dc)

_Originally posted by @jdearmas in https://github.com/RhinoSecurityLabs/pacu/issues/383#issuecomment-1877888290_

**Comment by DaveYesland** [comment]
the pull https://github.com/RhinoSecurityLabs/pacu/pull/358 added functionality to allow you to use jq in Pacu but jq does not appear to be a straight forward install on Windows and breaks the install.

**Comment by DaveYesland** [comment]
I do not think Pacu was ever really intended to be supported on Windows. But will leave this open for now, likely best to just close as no support for Windows.

**Comment by snotrauk** [comment]
this can be fixed on linux by running apt install gcc-12 g++-12
