### ISSUE TITLE
Adding ed25519 private key pattern

### ISSUE THREAD

**Issue by za** [RhinoSecurityLabs/pacu#396]
Hi there,

Can we add ed25519 private key pattern here? https://github.com/RhinoSecurityLabs/pacu/blob/master/pacu/core/secretfinder/regexs.json

ed25519 https://ed25519.cr.yp.to/software.html is getting more popular. GitHub also suggested to use this algorithm https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key

**Comment by DaveYesland** [comment]
Looks like this would just be a match for `-----BEGIN OPENSSH PRIVATE KEY-----`. Any other strings you think should be matched for this type of key?

**Comment by za** [comment]
> Looks like this would just be a match for `-----BEGIN OPENSSH PRIVATE KEY-----`. Any other strings you think should be matched for this type of key?

I couldn't find any other pattern other than that. 

I can prepare a PR for this.

**Comment by DaveYesland** [comment]
closed in https://github.com/RhinoSecurityLabs/pacu/pull/397
