### ISSUE TITLE
typo: `check_evn_secrets()` function?

### ISSUE THREAD

**Issue by za** [RhinoSecurityLabs/pacu#398]
Hi there,

Is this a typo on function name? `def check_evn_secrets(function):`
https://github.com/RhinoSecurityLabs/pacu/blob/1f3fc79234d1dfed8fb2ff753fd51185b0124b91/pacu/modules/lambda__enum/main.py#L142

Does `evn` refer as environment variable?

**Comment by DaveYesland** [comment]
Yeah looks like it was intended to be `env`

**Comment by za** [comment]
Thanks for the fix @DaveYesland
