### ISSUE TITLE
Format code using Black

### ISSUE THREAD

**Issue by za** [RhinoSecurityLabs/pacu#403]
Hi,

This is code style feedback. What do you think if the Python code are formatted using [Black](https://github.com/psf/black)?

Pros:
* consistent style
* single point of truth
* may attract more contributors as the code is easier to read

Cons:
* subjective
* opinionated

**Comment by za** [comment]
Hi @DaveYesland any opinion on this? Just in case you miss the notification although this is not urgent.

**Comment by DaveYesland** [comment]
Hello, yeah my initial thought is broadly reformatting all files blindly with Black at this time is not the best idea. I agree this is a good tool to use on future contributions and going forward to ensure a consistent styling. But I think at this time without considering this a little more on formatting parameters and time to review and test changes we will not be applying this across all the files in Pacu.
