### ISSUE TITLE
Sort imported Python modules alphabetically using isort

### ISSUE THREAD

**Issue by za** [RhinoSecurityLabs/pacu#405]
Hi there,

Any plan to use [isort](https://pycqa.github.io/isort/) to sort imported modules alphabetically? This will make the code easier to read as it's following Python best practice on importing modules.

Example:
```
diff --git a/pacu/core/lib.py b/pacu/core/lib.py
index 1fa9d0f..69660b4 100644
--- a/pacu/core/lib.py
+++ b/pacu/core/lib.py
@@ -1,8 +1,7 @@
 import contextlib
 import os
-from typing import Optional, cast, Callable, Generator, IO, Any
-
 from pathlib import Path
+from typing import IO, Any, Callable, Generator, Optional, cast
```

**Comment by DaveYesland** [comment]
There are certainly quite a few improvements which could be made to formatting and readability of Pacu's code. But for now formatting across the entire code base is not something we are planning to do.
