### ISSUE TITLE
Pacu is Unable to Start

### ISSUE THREAD

**Issue by rawsGit** [RhinoSecurityLabs/pacu#407]
Steps to Error: 
Navigate to Pacu directory
Execute sudo python3 cli.py 

First Run:
Pacu splashscreen did not appear on first run. First Run ends after answering the What would you like to name this new session? 

Second Run: 
Pacu splash screen appears, [0] & [1] options in Menu. I selected option [1] and got the following error. 
Error Starts Here: 
[2024-03-02 16:01:15] Pacu encountered an error while running the previous command. Check /root/.local/share/pacu/BlahLab/global_error_log.txt for technical details. [LOG LEVEL: MINIMAL]

    <class 'ValueError'>: time data '404: Not Found' does not match format '%Y-%m-%d'

Pacu is unable to start. Try backing up Pacu's sqlite.db file and deleting the old version. If the error persists, try reinstalling Pacu in a new directory.

Third Run:
Pacu splash screen appears, [0] & [1] options in Menu. I selected option [0] and got the same error mentioned in Second Run.

**Comment by jdearmas** [comment]
Hello! I've experience this error as well. The solution is to reinstall pacu completely.

If you installed pacu via pip, the following commands should fix your issue:
```
pip uninstall pacu
git clone https://github.com/RhinoSecurityLabs/pacu
cd pacu
poetry install
poetry run pacu
```

**Comment by rawsGit** [comment]
> Hello! I've experience this error as well. The solution is to reinstall pacu completely.
> 
> If you installed pacu via pip, the following commands should fix your issue:
> 
> ```
> pip uninstall pacu
> git clone https://github.com/RhinoSecurityLabs/pacu
> cd pacu
> poetry install
> poetry run pacu
> ```

Running pip uninstall pacu produces the following: 
fog@cloudb:~/tools/pacu$ pip uninstall pacu
WARNING: Skipping pacu as it is not installed.
fog@cloudb:~/tools/pacu$ which pacu
fog@cloudb:~/tools/pacu$ pwd
/home/fog/tools/pacu
fog@cloudb:~/tools/pacu$ uname -a
Linux cloudb 5.15.0-97-generic #107~20.04.1-Ubuntu SMP Fri Feb 9 14:20:11 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
fog@cloudb:~/tools/pacu$

**Comment by DaveYesland** [comment]
Did you try a fresh clone and `poetry install` of Pacu? Or `pip install pacu` after confirming there are no old versions installed?

**Comment by rawsGit** [comment]
I confirmed Pacu was definitely installed. Launching Pacu from commandline
produces Pacu splash screen and end-user prompt to begin new session or
continue with old. Both options, new and old, result with Pacu complaining.
I tore down the VM and will be rebuilding a new one, soon. I will post an
update next chance I get. Thanks.

**Comment by DaveYesland** [comment]
Ok just ensure you are running the latest version of Pacu. The error you described in the first post should not occur as that functionality was completely removed in version 1.5.0 https://github.com/RhinoSecurityLabs/pacu/releases/tag/v1.5.0

**Comment by DaveYesland** [comment]
Either install option _should_ install the latest version of Pacu: `pip install pacu` or `git clone` and `poetry install`
