### ISSUE TITLE
s3express-control.us-west-1.amazonaws.com doesn't respond

### ISSUE THREAD

**Issue by ertygiq** [RhinoSecurityLabs/pacu#414]
When running 'iam__bruteforce_permissions' module, the execution freezes for a while on 'Trying list_directory_buckets' task and then I get `Could not connect to the endpoint URL: "https://s3express-control.us-west-1.amazonaws.com/"`

Looks like it's checking for something which doesn't exist anymore.

**Comment by DaveYesland** [comment]
Here is the documentation on those endpoints: https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-express-networking.html#s3-express-endpoints

Does this cause Pacu to exit or fail with in error in some way? or does it just print that message and continue? I have not worked a bunch with `iam__bruteforce_permissions`, but it is intended to just "try" stuff and see if it works so several errors are expected if you do not have the permissions or the resources in the target account do not exist.

**Comment by DaveYesland** [comment]
Tried to reproduce this and running `iam__bruteforce_permissions` completed without any hanging or issues and found permissions. Closing for now, reopen if you have other steps to reproduce.
