### ISSUE TITLE
Improve installation/packaging process

### ISSUE THREAD

**Issue by nickpetrovic** [RhinoSecurityLabs/pacu#72]
Setup seems to use an unconventional installation method using a shell script to run `pip install`. Then you must call `python3 pacu.py` to start it up. It would be ideal to have the project be completely installed using pip e.g. 

```
pip install git+https://github.com/RhinoSecurityLabs/pacu.git
```

**Comment by SpenGietz** [comment]
I never have actually seen pip used like that, but seems like a much simpler solution. I'll check it out, thanks 👍

**Comment by nickptrvc** [comment]
Are you guys accepting pull requests?

**Comment by SpenGietz** [comment]
Yeah definitely, feel free to open one if you would like
