### ISSUE TITLE
AccessDeniedException not handled throughout enum_monitoring module

### ISSUE THREAD

**Issue by ansorren** [RhinoSecurityLabs/pacu#74]
Using a key that doesn't have permissions to make those calls will result in the AccessDeniedException, and since it's not passed in the module the enumeration will stop.

For example:
  <class 'botocore.exceptions.ClientError'>: An error occurred (AccessDeniedException) when calling the ListDetectors operation: User: arn:aws:iam::xxx:user/janedoe is not authorized to perform: guardduty:ListDetectors on resource: arn:aws:guardduty:ap-southeast-1:xxx:detector/*

**Comment by SpenGietz** [comment]
This fix has been merged into dev: https://github.com/RhinoSecurityLabs/pacu/pull/75

It will be merged into master next Monday or Tuesday I believe. Thanks for your report! I'll close this when it makes it to master

**Comment by SpenGietz** [comment]
Just now merged to master!
